### ISSUE TITLE
NPM Start (Help me to solve the issue please)

### ISSUE THREAD

**Issue by harshp45** [gregsqueeb/consultDash#8]
pi@riot6:~/consultDash $ npm start

> hello-world@ start /home/pi/consultDash
> node server.js

/home/pi/consultDash/node_modules/serialport/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (/home/pi/consultDash/node_modules/serialport/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/pi/consultDash/node_modules/serialport/lib/bindings.js:3:35)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

npm ERR! Linux 4.9.35-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! hello-world@ start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hello-world@ start script 'node server.js'.
npm ERR! This is most likely a problem with the hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/consultDash/npm-debug.log

**Comment by gregsqueeb** [comment]
Hmm, is your USB serial port cable connected to the RPI? Another thing you could check is I just realized I did not have a version of node specified in the repo, and if your version of node is newer than v5.12 then the version of serialport that I have included with the package.json will not work. Try downgrading your node to v5.12 and re `npm install`ing the packages and running again
