### ISSUE TITLE
Can find module ´serial port´

### ISSUE THREAD

**Issue by rafalbrz71** [gregsqueeb/consultDash#9]
Greg, 

Can you point me in the right direction. I´m new to Java...

pi@raspberrypi:~/consultDash $ npm run dev

> hello-world@ dev /home/pi/consultDash
> NODE_ENV=development node server.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'serialport'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/consultDash/server.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-world@ dev: `NODE_ENV=development node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hello-world@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-09-05T00_55_47_791Z-debug.log
pi@raspberrypi:~/consultDash $

**Comment by rafalbrz71** [comment]
found solution like this
"sudo npm install serialport --unsafe-perm --build-from-source"

**Comment by Xximway2rawxX** [comment]
I have the same problem did anyone find a solution?
